### ISSUE TITLE
Infinity2o.com Screenshots

### ISSUE THREAD

**Issue by Hunter690** [Hunter690/CV#1]

**Comment by Hunter690** [comment]
Attempt #2

![image](https://user-images.githubusercontent.com/24757872/38591885-ac8e6b70-3cfe-11e8-8849-0e1423fb6c53.png)

**Comment by Hunter690** [comment]
Attempt #3

![image](https://user-images.githubusercontent.com/24757872/38591997-3c13d8b6-3cff-11e8-97c8-2235e71e286b.png)

**Comment by Hunter690** [comment]
Attempt #4

![image](https://user-images.githubusercontent.com/24757872/38592171-2526bfb4-3d00-11e8-99cb-fc1f28905e83.png)

**Comment by Hunter690** [comment]
![image](https://user-images.githubusercontent.com/24757872/38592822-e5c67784-3d03-11e8-930d-ab344b3013bb.png)

**Comment by quinnliu** [comment]
<img width="747" alt="screen shot 2018-04-11 at 7 41 42 am" src="https://user-images.githubusercontent.com/2585159/38617158-e0d0db72-3d5b-11e8-8c2c-e5040d2dfe51.png">

**Comment by quinnliu** [comment]
<img width="747" alt="screen shot 2018-04-11 at 7 41 42 am" src="https://user-images.githubusercontent.com/2585159/38620976-7676a2d4-3d65-11e8-8448-1cd6833b0815.png">

**Comment by quinnliu** [comment]
<img width="663" alt="screen shot 2018-04-11 at 8 54 40 am" src="https://user-images.githubusercontent.com/2585159/38621233-0a2b0e7a-3d66-11e8-92f8-0987f122fbbd.png">

**Comment by quinnliu** [comment]
<img width="717" alt="screen shot 2018-04-11 at 9 15 37 am" src="https://user-images.githubusercontent.com/2585159/38622587-1cc4050c-3d69-11e8-9953-2945887cd73c.png">

**Comment by quinnliu** [comment]
<img width="725" alt="screen shot 2018-04-11 at 9 51 50 am" src="https://user-images.githubusercontent.com/2585159/38624600-144881fa-3d6e-11e8-8fc3-203c925d04c4.png">

**Comment by quinnliu** [comment]
<img width="711" alt="screen shot 2018-04-11 at 10 02 29 am" src="https://user-images.githubusercontent.com/2585159/38625186-823b5876-3d6f-11e8-89c3-17ed4c7b65e8.png">
