### ISSUE TITLE
Email Pictures

### ISSUE THREAD

**Issue by Hunter690** [Hunter690/CV#3]
![imgs_bannerbottom](https://user-images.githubusercontent.com/24757872/43986313-d3ef7412-9cd4-11e8-8c4a-582b201a2a05.png)
![imgs_bannertop](https://user-images.githubusercontent.com/24757872/43986314-d405c0e6-9cd4-11e8-8394-d965def04171.png)
![logo](https://user-images.githubusercontent.com/24757872/43986315-d41857d8-9cd4-11e8-902d-5ceb9d7cb367.png)

**Comment by quinnliu** [comment]
FUCK YA!!!!

**Comment by Hunter690** [comment]
![higher quality screenshot](https://user-images.githubusercontent.com/24757872/44041902-8aba67e0-9ee4-11e8-914b-ea758a6ce5d6.PNG)

**Comment by Hunter690** [comment]
![linkedin](https://user-images.githubusercontent.com/24757872/44111673-b5b6dd72-9fc8-11e8-916f-6accfed10b7c.png)

**Comment by Hunter690** [comment]
![linkedin 1](https://user-images.githubusercontent.com/24757872/44111718-d2191944-9fc8-11e8-9279-3c9d63b5bb08.png)

**Comment by Hunter690** [comment]
![linkedin 2](https://user-images.githubusercontent.com/24757872/44111793-088fcb30-9fc9-11e8-8b44-f43e6216d696.png)

**Comment by Hunter690** [comment]
![github](https://user-images.githubusercontent.com/24757872/44112399-9f76e05a-9fca-11e8-8a1d-a3d3f3979bc0.png)

**Comment by Hunter690** [comment]
![love](https://user-images.githubusercontent.com/24757872/44114955-3b8c19c2-9fd2-11e8-9da9-4ac7b4a0fac2.png)

**Comment by Hunter690** [comment]
![hand1](https://user-images.githubusercontent.com/24757872/44218651-c5e60d80-a13f-11e8-8ea9-19e836215e47.png)

**Comment by Hunter690** [comment]
![hand1 1](https://user-images.githubusercontent.com/24757872/44219378-7a346380-a141-11e8-95e1-aa38fd5a5b71.png)

**Comment by Hunter690** [comment]
![hand1](https://user-images.githubusercontent.com/24757872/44354773-5b4f0d80-a470-11e8-9edc-0c0c33e43a8a.png)

**Comment by Hunter690** [comment]
![hand1](https://user-images.githubusercontent.com/24757872/44631628-66a0ae00-a934-11e8-95d2-f8627a082cd1.png)

**Comment by Hunter690** [comment]
![hand1 1](https://user-images.githubusercontent.com/24757872/44631630-6f917f80-a934-11e8-953b-9c8066b62044.png)

**Comment by Hunter690** [comment]
![hand1 2](https://user-images.githubusercontent.com/24757872/44631693-3279bd00-a935-11e8-909d-12b151692c64.png)
